export { default as HomePage } from './Home'
export { default as CatalogPage } from './Catalog'
export { default as LoginPage } from './Login'
export { default as RegisterPage } from './Register'
export { default as DetailPage } from './Detail'
export { default as CheckoutPage } from './Checkout'
export { default as CartPage } from './Cart'